### ISSUE TITLE
defintion from other file

### ISSUE THREAD

**Issue by yc90s** [xxxg0001/lua-for-vscode#1]
It can't find defintion from other files after I have been set the lua path to workspace settings.

**Comment by lgcagithub** [comment]
@1050676515 In addition to set the `luapath`, you should also set the `includekeyword`. In fact, the extension still can't find defintion from other files if you import other files by `require("other_file")`, because the extension will search the path `${luapath}/other_file`, not `${luapath}/other_file.lua`. However, lua interpreter will throw error for `require("other_file.lua")`. This is a bug that we are fixing now. Coming soon.

**Comment by yc90s** [comment]
yes，the problem is the difference between require("otherfile") and require("otherfile.lua").
And I found another bug. When there are some files are opened, goto definition in one of them, and then I choose another one of them, the definitions don't update until I close the file and reopen it.

**Comment by lgcagithub** [comment]
@1050676515 Yes, I got the same problem too. This is another bug we are fixing now. Thanks for your issue.

**Comment by yc90s** [comment]
@lgcagithub This is really a very useful tool for lua.
